name: new-env
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - pandas
  - numpy
  - duckdb=1.1.1
  - pip
  - google-cloud-storage
  - joblib
  - gcsfs
  - scikit-learn
  - matplotlib
  - pyarrow
  - fastparquet
  - prefect
  - pip:
    - transformers
    - tensorFlow >= 2.0
    - yfinance==0.2.18
    - fredapi